### ISSUE TITLE
todo's from april10 steering committee meeting

### ISSUE THREAD

**Issue by timm** [se-analytics/se-analytics.github.io#1]
Olga

- [x]   Fse people to organize easy chair
- [x]     swing thru current docs looking for hiccups
- [x]    ping sonja
- [x] CFP 

Timm

- [x] Peggy said yes
- [ ] explore others
- [ ] get pub office

**Comment by obaysal** [comment]
I am done with the following tasks:

- [x] Fse people to organize easy chair (EasyChair installation is done)
- [x] swing thru current docs looking for hiccups (website is updated)
- [x] CFP (sent to Damian)

**Comment by obaysal** [comment]
- [x] Sent email to Sonia
